/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.presentacion;

/**
 *
 * @author Usuario
 */
public class MetodoPago extends javax.swing.JFrame {

    /**
     * Creates new form MetodoPago
     */
    public MetodoPago() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        subTitulo = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        separadorApellido = new javax.swing.JSeparator();
        separadorNombre = new javax.swing.JSeparator();
        direccion = new javax.swing.JTextField();
        separadorDireccion = new javax.swing.JSeparator();
        tarjeta = new javax.swing.JTextField();
        separadorTarjeta = new javax.swing.JSeparator();
        fechaCaducidad = new javax.swing.JTextField();
        separadorFechaCaducidad = new javax.swing.JSeparator();
        cvv = new javax.swing.JTextField();
        separadorCvv = new javax.swing.JSeparator();
        botonPagar = new utils.RoundedPanel();
        jLabel7 = new javax.swing.JLabel();
        roundedPanel2 = new utils.RoundedPanel();
        jLabel8 = new javax.swing.JLabel();
        botonOxxo = new utils.RoundedPanel();
        jLabel9 = new javax.swing.JLabel();
        botonPaypal = new utils.RoundedPanel();
        jLabel5 = new javax.swing.JLabel();
        leyendaMetodoDePago = new javax.swing.JLabel();
        panelAzul = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(22, 36, 64));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/B (1).png"))); // NOI18N
        logo.setText("jLabel4");
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 350, 430));

        titulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(234, 205, 54));
        titulo.setText("Elige cómo pagar");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 26, -1, -1));

        subTitulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        subTitulo.setForeground(new java.awt.Color(234, 205, 54));
        subTitulo.setText("Tarjeta de debito o credito");
        jPanel1.add(subTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 109, -1, -1));

        nombre.setBackground(new java.awt.Color(22, 36, 64));
        nombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        nombre.setForeground(new java.awt.Color(161, 167, 179));
        nombre.setText("Nombre");
        nombre.setBorder(null);
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 179, 147, -1));

        apellido.setBackground(new java.awt.Color(22, 36, 64));
        apellido.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        apellido.setForeground(new java.awt.Color(161, 167, 179));
        apellido.setText("Apellido");
        apellido.setBorder(null);
        apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoActionPerformed(evt);
            }
        });
        jPanel1.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 179, 147, -1));

        separadorApellido.setForeground(new java.awt.Color(161, 167, 179));
        separadorApellido.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel1.add(separadorApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 209, 153, 20));

        separadorNombre.setForeground(new java.awt.Color(161, 167, 179));
        separadorNombre.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel1.add(separadorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 209, 147, 20));

        direccion.setBackground(new java.awt.Color(22, 36, 64));
        direccion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        direccion.setForeground(new java.awt.Color(161, 167, 179));
        direccion.setText("Direccion");
        direccion.setBorder(null);
        direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionActionPerformed(evt);
            }
        });
        jPanel1.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 258, 308, -1));

        separadorDireccion.setForeground(new java.awt.Color(161, 167, 179));
        separadorDireccion.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel1.add(separadorDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 288, 410, 20));

        tarjeta.setBackground(new java.awt.Color(22, 36, 64));
        tarjeta.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        tarjeta.setForeground(new java.awt.Color(161, 167, 179));
        tarjeta.setText("Tarjeta");
        tarjeta.setBorder(null);
        tarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarjetaActionPerformed(evt);
            }
        });
        jPanel1.add(tarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 326, 296, -1));

        separadorTarjeta.setForeground(new java.awt.Color(161, 167, 179));
        separadorTarjeta.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel1.add(separadorTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 356, 410, 20));

        fechaCaducidad.setBackground(new java.awt.Color(22, 36, 64));
        fechaCaducidad.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        fechaCaducidad.setForeground(new java.awt.Color(161, 167, 179));
        fechaCaducidad.setText("Fecha");
        fechaCaducidad.setBorder(null);
        fechaCaducidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaCaducidadActionPerformed(evt);
            }
        });
        jPanel1.add(fechaCaducidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 413, 80, -1));

        separadorFechaCaducidad.setForeground(new java.awt.Color(161, 167, 179));
        separadorFechaCaducidad.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel1.add(separadorFechaCaducidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 443, 80, 20));

        cvv.setBackground(new java.awt.Color(22, 36, 64));
        cvv.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        cvv.setForeground(new java.awt.Color(161, 167, 179));
        cvv.setText("CVV");
        cvv.setBorder(null);
        cvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvvActionPerformed(evt);
            }
        });
        jPanel1.add(cvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 413, 80, -1));

        separadorCvv.setForeground(new java.awt.Color(161, 167, 179));
        separadorCvv.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel1.add(separadorCvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 443, 80, 20));

        botonPagar.setBackground(new java.awt.Color(234, 205, 54));
        botonPagar.setRoundBottomLeft(30);
        botonPagar.setRoundBottomRight(30);
        botonPagar.setRoundTopLeft(30);
        botonPagar.setRoundTopRight(30);

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(26, 43, 76));
        jLabel7.setText("Pagar");

        roundedPanel2.setBackground(new java.awt.Color(234, 205, 54));
        roundedPanel2.setRoundBottomLeft(30);
        roundedPanel2.setRoundBottomRight(30);
        roundedPanel2.setRoundTopLeft(30);
        roundedPanel2.setRoundTopRight(30);

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(26, 43, 76));
        jLabel8.setText("Pagar");

        javax.swing.GroupLayout roundedPanel2Layout = new javax.swing.GroupLayout(roundedPanel2);
        roundedPanel2.setLayout(roundedPanel2Layout);
        roundedPanel2Layout.setHorizontalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        roundedPanel2Layout.setVerticalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout botonPagarLayout = new javax.swing.GroupLayout(botonPagar);
        botonPagar.setLayout(botonPagarLayout);
        botonPagarLayout.setHorizontalGroup(
            botonPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonPagarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(botonPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(botonPagarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(roundedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        botonPagarLayout.setVerticalGroup(
            botonPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonPagarLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 7, Short.MAX_VALUE))
            .addGroup(botonPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(botonPagarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(roundedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(botonPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, 140, 50));

        botonOxxo.setBackground(new java.awt.Color(234, 205, 54));
        botonOxxo.setRoundBottomLeft(40);
        botonOxxo.setRoundBottomRight(40);
        botonOxxo.setRoundTopLeft(40);
        botonOxxo.setRoundTopRight(40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/oxxo.png"))); // NOI18N

        javax.swing.GroupLayout botonOxxoLayout = new javax.swing.GroupLayout(botonOxxo);
        botonOxxo.setLayout(botonOxxoLayout);
        botonOxxoLayout.setHorizontalGroup(
            botonOxxoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonOxxoLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(22, 22, 22))
        );
        botonOxxoLayout.setVerticalGroup(
            botonOxxoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonOxxoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(16, 16, 16))
        );

        jPanel1.add(botonOxxo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, 110, 50));

        botonPaypal.setBackground(new java.awt.Color(234, 205, 54));
        botonPaypal.setRoundBottomLeft(40);
        botonPaypal.setRoundBottomRight(40);
        botonPaypal.setRoundTopLeft(40);
        botonPaypal.setRoundTopRight(40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/paypal (1).png"))); // NOI18N

        javax.swing.GroupLayout botonPaypalLayout = new javax.swing.GroupLayout(botonPaypal);
        botonPaypal.setLayout(botonPaypalLayout);
        botonPaypalLayout.setHorizontalGroup(
            botonPaypalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonPaypalLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(31, 31, 31))
        );
        botonPaypalLayout.setVerticalGroup(
            botonPaypalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonPaypalLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        jPanel1.add(botonPaypal, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 520, 100, 50));

        leyendaMetodoDePago.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        leyendaMetodoDePago.setForeground(new java.awt.Color(234, 205, 54));
        leyendaMetodoDePago.setText("Eliga otro metodo de pago");
        jPanel1.add(leyendaMetodoDePago, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, -1, -1));

        panelAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo (4).png"))); // NOI18N
        panelAzul.setText("jLabel6");
        jPanel1.add(panelAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 530, 590));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (2) (1).jpg"))); // NOI18N
        fondo.setText("jLabel1");
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoActionPerformed

    private void direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionActionPerformed

    private void roundedPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_roundedPanel1MouseClicked

    private void tarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarjetaActionPerformed

    private void fechaCaducidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaCaducidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaCaducidadActionPerformed

    private void cvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvvActionPerformed

    private void roundedPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_roundedPanel2MouseClicked

    private void roundedPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_roundedPanel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MetodoPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MetodoPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MetodoPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MetodoPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MetodoPago().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    private utils.RoundedPanel botonOxxo;
    private utils.RoundedPanel botonPagar;
    private utils.RoundedPanel botonPaypal;
    private javax.swing.JTextField cvv;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField fechaCaducidad;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel leyendaMetodoDePago;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel panelAzul;
    private utils.RoundedPanel roundedPanel2;
    private javax.swing.JSeparator separadorApellido;
    private javax.swing.JSeparator separadorCvv;
    private javax.swing.JSeparator separadorDireccion;
    private javax.swing.JSeparator separadorFechaCaducidad;
    private javax.swing.JSeparator separadorNombre;
    private javax.swing.JSeparator separadorTarjeta;
    private javax.swing.JLabel subTitulo;
    private javax.swing.JTextField tarjeta;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
