/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.presentacion;

import DTOs.MembresiaDTO;
import DTOs.MetodoPagoDTO;
import control.ControlGUI;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class MetodoPago extends javax.swing.JFrame {

    /**
     * Creates new form MetodoPago
     */
    public MetodoPago() {
        initComponents();
        agregarCampoTexto(nombre, "Nombre");
        agregarCampoTexto(apellido, "Apellido");
        agregarCampoTexto(direccion, "Direccion");
        agregarCampoTexto(cvv, "CVV");
        agregarCampoTexto(tarjeta, "Tarjeta");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mesCaducidad = new com.toedter.calendar.JMonthChooser();
        anioCaducidad = new com.toedter.calendar.JYearChooser();
        btnSiguiente = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        subTitulo = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        separadorApellido = new javax.swing.JSeparator();
        separadorNombre = new javax.swing.JSeparator();
        cvv = new javax.swing.JPasswordField();
        direccion = new javax.swing.JTextField();
        separadorDireccion = new javax.swing.JSeparator();
        tarjeta = new javax.swing.JTextField();
        separadorTarjeta = new javax.swing.JSeparator();
        separadorFechaCaducidad = new javax.swing.JSeparator();
        separadorCvv = new javax.swing.JSeparator();
        leyendaMetodoDePago = new javax.swing.JLabel();
        panelAzul = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(22, 36, 64));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(mesCaducidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, -1));
        jPanel1.add(anioCaducidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, -1, -1));

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 500, 120, 40));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/B (1).png"))); // NOI18N
        logo.setText("jLabel4");
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 350, 430));

        titulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(234, 205, 54));
        titulo.setText("Elige cómo pagar");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 26, -1, -1));

        subTitulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        subTitulo.setForeground(new java.awt.Color(234, 205, 54));
        subTitulo.setText("Tarjeta de debito o credito");
        jPanel1.add(subTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 109, -1, -1));

        nombre.setBackground(new java.awt.Color(22, 36, 64));
        nombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        nombre.setForeground(new java.awt.Color(161, 167, 179));
        nombre.setText("Nombre");
        nombre.setBorder(null);
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 179, 147, -1));

        apellido.setBackground(new java.awt.Color(22, 36, 64));
        apellido.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        apellido.setForeground(new java.awt.Color(161, 167, 179));
        apellido.setText("Apellido");
        apellido.setBorder(null);
        apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoActionPerformed(evt);
            }
        });
        jPanel1.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 179, 147, -1));

        separadorApellido.setForeground(new java.awt.Color(161, 167, 179));
        separadorApellido.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel1.add(separadorApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 209, 153, 20));

        separadorNombre.setForeground(new java.awt.Color(161, 167, 179));
        separadorNombre.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel1.add(separadorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 209, 147, 20));

        cvv.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        cvv.setText("jPasswordField1");
        cvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvvActionPerformed(evt);
            }
        });
        jPanel1.add(cvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 80, 30));

        direccion.setBackground(new java.awt.Color(22, 36, 64));
        direccion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        direccion.setForeground(new java.awt.Color(161, 167, 179));
        direccion.setText("Direccion");
        direccion.setBorder(null);
        direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionActionPerformed(evt);
            }
        });
        jPanel1.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 258, 308, -1));

        separadorDireccion.setForeground(new java.awt.Color(161, 167, 179));
        separadorDireccion.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel1.add(separadorDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 288, 410, 20));

        tarjeta.setBackground(new java.awt.Color(22, 36, 64));
        tarjeta.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        tarjeta.setForeground(new java.awt.Color(161, 167, 179));
        tarjeta.setText("Tarjeta");
        tarjeta.setBorder(null);
        tarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarjetaActionPerformed(evt);
            }
        });
        jPanel1.add(tarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 326, 296, -1));

        separadorTarjeta.setForeground(new java.awt.Color(161, 167, 179));
        separadorTarjeta.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel1.add(separadorTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 356, 410, 20));

        separadorFechaCaducidad.setForeground(new java.awt.Color(161, 167, 179));
        separadorFechaCaducidad.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel1.add(separadorFechaCaducidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 443, 80, 20));

        separadorCvv.setForeground(new java.awt.Color(161, 167, 179));
        separadorCvv.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel1.add(separadorCvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 443, 80, 20));

        leyendaMetodoDePago.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        leyendaMetodoDePago.setForeground(new java.awt.Color(234, 205, 54));
        leyendaMetodoDePago.setText("Eliga otro metodo de pago");
        jPanel1.add(leyendaMetodoDePago, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, -1, -1));

        panelAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo (4).png"))); // NOI18N
        panelAzul.setText("jLabel6");
        jPanel1.add(panelAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 530, 590));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (2) (1).jpg"))); // NOI18N
        fondo.setText("jLabel1");
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed

    }//GEN-LAST:event_nombreActionPerformed

    private void apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoActionPerformed

    }//GEN-LAST:event_apellidoActionPerformed

    private void direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionActionPerformed

    }//GEN-LAST:event_direccionActionPerformed

    private void roundedPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_roundedPanel1MouseClicked

    private void tarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarjetaActionPerformed

    }//GEN-LAST:event_tarjetaActionPerformed

    private void roundedPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_roundedPanel2MouseClicked

    private void roundedPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_roundedPanel3MouseClicked

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        String nombreTarjeta = limpiarTexto(nombre, "Nombre");
        String apellidoTarjeta = limpiarTexto(apellido, "Apellido");
        String codigoSeguridad = limpiarTexto(cvv, "CVV");
        String direccionTarjeta = limpiarTexto(direccion, "Direccion");
        String numeroTarjeta = limpiarTexto(tarjeta, "Tarjeta");
        int anio = anioCaducidad.getYear();
        int mes = mesCaducidad.getMonth();
        MetodoPagoDTO pago = new MetodoPagoDTO(nombreTarjeta, apellidoTarjeta, direccionTarjeta, numeroTarjeta, codigoSeguridad, anio, mes);
        MembresiaDTO membresia = ControlGUI.getInstancia().getMembresiaSeleccionada();
        ControlGUI.getInstancia().procesarPago(pago, membresia);

    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void cvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MetodoPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MetodoPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MetodoPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MetodoPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MetodoPago().setVisible(true);
            }
        });
    }

    private void agregarCampoTexto(JTextField field, String campoTexto) {
        field.setText(campoTexto);

        field.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (field.getText().equals(campoTexto)) {
                    field.setText("");
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (field.getText().isEmpty()) {
                    field.setText(campoTexto);
                }
            }
        });
    }

    private String limpiarTexto(JTextField field, String campoTexto) {
        String text = field.getText().trim();
        return text.equals(campoTexto) ? null : text;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JYearChooser anioCaducidad;
    private javax.swing.JTextField apellido;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JPasswordField cvv;
    private javax.swing.JTextField direccion;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel leyendaMetodoDePago;
    private javax.swing.JLabel logo;
    private com.toedter.calendar.JMonthChooser mesCaducidad;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel panelAzul;
    private javax.swing.JSeparator separadorApellido;
    private javax.swing.JSeparator separadorCvv;
    private javax.swing.JSeparator separadorDireccion;
    private javax.swing.JSeparator separadorFechaCaducidad;
    private javax.swing.JSeparator separadorNombre;
    private javax.swing.JSeparator separadorTarjeta;
    private javax.swing.JLabel subTitulo;
    private javax.swing.JTextField tarjeta;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
