/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.presentacion;

import DTOs.MembresiaDTO;

/**
 *
 * @author devor
 */
public class PanelMembresia extends javax.swing.JPanel {
    private MembresiaDTO membresia;
    /**
     * Creates new form TemplateMembresia
     */
    public PanelMembresia(MembresiaDTO membresia) {
        this.membresia = membresia;
        initComponents();
        setupPanel();
    }
    
    private void setupPanel(){
        
        LabelNombre.setText(membresia.getNombre());
        LabelDescripcion.setText(membresia.getDescripcion());
        LabelMonto.setText(String.format("$%.2f",  membresia.getMonto()));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelNombre = new javax.swing.JLabel();
        LabelDescripcion = new javax.swing.JLabel();
        LabelMonto = new javax.swing.JLabel();

        LabelNombre.setText("Nombre ");

        LabelDescripcion.setText("jLabel1");

        LabelMonto.setText("Monto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelMonto)
                    .addComponent(LabelDescripcion)
                    .addComponent(LabelNombre))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(LabelNombre)
                .addGap(36, 36, 36)
                .addComponent(LabelDescripcion)
                .addGap(38, 38, 38)
                .addComponent(LabelMonto)
                .addContainerGap(114, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelDescripcion;
    private javax.swing.JLabel LabelMonto;
    private javax.swing.JLabel LabelNombre;
    // End of variables declaration//GEN-END:variables
}
