/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.presentacion;

import DTOs.GeneroDTO;

/**
 *
 * @author devor
 */

public class PanelGenero extends javax.swing.JPanel {

    private GeneroDTO genero;
    
    public PanelGenero(GeneroDTO genero) {
        this.genero = genero;
        initComponents();
        LabelNombre.setText(genero.getNombre());
        CheckBoxSeleccionar.setSelected(genero.isSeleccionado());

        CheckBoxSeleccionar.addActionListener(e -> {
            genero.setSeleccionado(CheckBoxSeleccionar.isSelected());
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelNombre = new javax.swing.JLabel();
        CheckBoxSeleccionar = new javax.swing.JCheckBox();

        LabelNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LabelNombre.setText("Nombre Categoria");

        CheckBoxSeleccionar.setText("Seleccionar");
        CheckBoxSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(LabelNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(CheckBoxSeleccionar)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addComponent(LabelNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CheckBoxSeleccionar)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CheckBoxSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxSeleccionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxSeleccionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxSeleccionar;
    private javax.swing.JLabel LabelNombre;
    // End of variables declaration//GEN-END:variables
}
