/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.presentacion;

import DTOs.GeneroDTO;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author devor a
 */
public class SeleccionGeneros extends javax.swing.JFrame {

    private List<GeneroDTO> generos;
    private int indiceActual = 0;
    private JEditorPane jEditorPane1; // Añade esta línea
    private PanelGenero panelGeneroActual;

    /**
     * Creates new form SeleccionGeneros
     */
    public SeleccionGeneros() {
        initComponents();
        inicializarGeneros();
        configurarInterfaz();
    }

    private void inicializarGeneros() {
        generos = new ArrayList<>();
        generos.add(new GeneroDTO("Drama"));

        generos.add(new GeneroDTO("Terror"));
        generos.add(new GeneroDTO("Comedia"));
    }

  private void configurarInterfaz() {
       
        panelGeneroActual = new PanelGenero(generos.get(0));
        jPanelContenedor.removeAll(); 
        jPanelContenedor.add(panelGeneroActual);
        jPanelContenedor.revalidate();
        jPanelContenedor.repaint();
        jPanelGeneroContainer = new JPanel();
        jPanelGeneroContainer.setLayout(new BorderLayout());
        jPanel1.add(jPanelGeneroContainer, BorderLayout.CENTER);
        
        mostrarGeneroActual();
    }
  
 private void mostrarGeneroActual() {
        jPanelGeneroContainer.removeAll();
        PanelGenero panel = new PanelGenero(generos.get(indiceActual));
        jPanelGeneroContainer.add(panel);
        jPanelGeneroContainer.revalidate();
        jPanelGeneroContainer.repaint();
    }
  
    private void actualizarVisualizacionGeneros() {
    // Limpia el contenedor
    jPanelContenedor.removeAll();
    
    // Crea y añade el panel del género actual
    GeneroDTO generoActual = generos.get(indiceActual);
    panelGeneroActual = new PanelGenero(generoActual);
    jPanelContenedor.add(panelGeneroActual);
    
    // Actualiza la interfaz
    jPanelContenedor.revalidate();
    jPanelContenedor.repaint();
}
    
      private void cambiarGenero(int direccion) {
        indiceActual = (indiceActual + direccion + generos.size()) % generos.size();
        mostrarGeneroActual();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContenedor = new javax.swing.JPanel();
        jPanelGeneroContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanelContenedorLayout = new javax.swing.GroupLayout(jPanelContenedor);
        jPanelContenedor.setLayout(jPanelContenedorLayout);
        jPanelContenedorLayout.setHorizontalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelContenedorLayout.setVerticalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        javax.swing.GroupLayout jPanelGeneroContainerLayout = new javax.swing.GroupLayout(jPanelGeneroContainer);
        jPanelGeneroContainer.setLayout(jPanelGeneroContainerLayout);
        jPanelGeneroContainerLayout.setHorizontalGroup(
            jPanelGeneroContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelGeneroContainerLayout.setVerticalGroup(
            jPanelGeneroContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelGeneroContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionGeneros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionGeneros().setVisible(true);
            }

        });
    }

    public List<GeneroDTO> getGenerosSeleccionados() {
        List<GeneroDTO> seleccionados = new ArrayList<>();
        for (GeneroDTO genero : generos) {
            if (genero.isSeleccionado()) {
                seleccionados.add(genero);
            }
        }
        return seleccionados;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelContenedor;
    private javax.swing.JPanel jPanelGeneroContainer;
    // End of variables declaration//GEN-END:variables
}
